// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("ch_body_gk_ro635");
	self attach("ch_head_gk_ro635", "", true);
	self attach("ch_hair_gk_ro635", "", true);
	self.headModel = "ch_head_gk_ro635";
	self.voice = "taskforce";
}

precache()
{
	precacheModel("ch_body_gk_ro635");
	precacheModel("ch_head_gk_ro635");
	precacheModel("ch_hair_gk_ro635");
}
