// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("ch_body_gk_rfb");
	self attach("ch_head_gk_rfb", "", true);
	self attach("ch_hair_gk_rfb", "", true);
	self.headModel = "ch_head_gk_rfb";
	self.voice = "american";
}

precache()
{
	precacheModel("ch_body_gk_rfb");
	precacheModel("ch_head_gk_rfb");
	precacheModel("ch_hair_gk_rfb");
}
