// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("ch_coop_gk_m4a1");
	self setViewmodel("viewhands_tf141");
	self.voice = "taskforce";
}

precache()
{
	precacheModel("ch_coop_gk_m4a1");
	precacheModel("viewhands_tf141");
}
